// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/grand-crown-auth/Current.tsx": () => import("../components/mockups/grand-crown-auth/Current.tsx"),
  "./components/mockups/grand-crown-auth/Reference.tsx": () => import("../components/mockups/grand-crown-auth/Reference.tsx")
};
